/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mspindler' at '9/28/16 12:04 PM' with Gradle 2.14.1
 *
 * @author mspindler, @date 9/28/16 12:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
